// Dashboard published dataset types.
// These describe the JSON files generated by prepare-data.ts
// and consumed by the dashboard UI at runtime.

// Index file: public/data/index.json
export interface DashboardIndex {
  generatedAt: string;
  dateRange: { start: string; end: string };
  totals: {
    repos: number;
    stars: number;
    forks: number;
    views: number;
    clones: number;
  };
  repos: RepoSummary[];
}

export interface RepoSummary {
  id: number;
  fullName: string;
  language: string | null;
  description: string | null;
  stars: number;
  forks: number;
  viewsThisWeek: number;
  clonesThisWeek: number;
  starsGainedThisWeek: number;
}

// Per-repo file: public/data/repos/{owner}/{repo}.json
export interface RepoTimeSeries {
  id: number;
  fullName: string;
  days: DayEntry[];
  weekOverWeek: WeekOverWeek;
}

export interface DayEntry {
  date: string;
  views: number;
  viewsUnique: number;
  clones: number;
  clonesUnique: number;
  stars: number;
  forks: number;
}

export interface WeekOverWeek {
  views: Delta;
  clones: Delta;
  stars: Delta;
}

export interface Delta {
  current: number;
  previous: number;
  change: number; // percentage, e.g. 0.5 = +50%
}

// Contributions: public/data/contributions.json
export interface ContributionsData {
  days: { date: string; count: number }[];
}

// Referrers: public/data/referrers.json
export interface ReferrersData {
  date: string; // window date
  repos: Record<
    string,
    {
      // keyed by fullName
      referrers: { referrer: string; count: number; uniques: number }[];
      paths: {
        path: string;
        title: string;
        count: number;
        uniques: number;
      }[];
    }
  >;
}
